export const sample_foods = [
  {
    id: "1",
    name: "Pizza Pepperoni",
    cookTime: "10-20",
    price: 110,
    favorite: false,
    origins: ["italy"],
    stars: 4.5,
    imageUrl: "food-1.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
  {
    id: "2",
    name: "Meatball",
    price: 160,
    cookTime: "20-30",
    favorite: true,
    origins: ["persia", "china"],
    stars: 5,
    imageUrl: "food-2.jpg",
    tags: ["SlowFood", "Lunch"],
  },
  {
    id: "3",
    name: "Hamburger",
    price: 250,
    cookTime: "10-15",
    favorite: false,
    origins: ["Germany", "USA"],
    stars: 3.5,
    imageUrl: "food-3.jpg",
    tags: ["FastFood", "Hamburger"],
  },
  {
    id: "4",
    name: "Fried Potatoes",
    price: 50,
    cookTime: "15-20",
    favorite: true,
    origins: ["Belgium", "France"],
    stars: 3,
    imageUrl: "food-4.jpg",
    tags: ["FastFood", "Fry"],
  },
  {
    id: "5",
    name: "Chicken Soup",
    price: 200,
    cookTime: "40-50",
    favorite: false,
    origins: ["india", "China"],
    stars: 3.5,
    imageUrl: "food-5.jpg",
    tags: ["SlowFood", "Soup"],
  },
  {
    id: "6",
    name: "Vegetables Pizza",
    price: 100,
    cookTime: "40-50",
    favorite: false,
    origins: ["italy", "India"],
    stars: 4.0,
    imageUrl: "food-6.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
];
export const sample_tags = [
  { name: "All", count: 6 },
  { name: "FastFood", count: 4 },
  { name: "Pizza", count: 2 },
  { name: "Lunch", count: 3 },
  { name: "SlowFood", count: 2 },
  { name: "Hamburger", count: 1 },
  { name: "Fry", count: 1 },
  { name: "Soup", count: 1 },
];

export const sample_users = [
  {
    id: 1,
    name: "Tonmoy Biswas",
    email: "tonmoy@gmail.com",
    password: "123",
    address: "Uttara,Dhaka-1230",
    isAdmin: true,
  },
  {
    id: 2,
    name: "Jawadul Hasan",
    email: "jawad@gmail.com",
    password: "123",
    address: "Mirpur",
    isAdmin: false,
  },
  {
    id: 3,
    name: "Saurov",
    email: "saurov@gmail.com",
    password: "123",
    address: "Bashundhara",
    isAdmin: false,
  },
  {
    id: 4,
    name: "Snigdha Biswas",
    email: "snigdha@gmail.com",
    password: "123",
    address: "Uttara-Dhaka",
    isAdmin: false,
  },
];
